version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:XBkGexHLYzrmnsSALzHRYBKCMkQOvfzD@gondola.proxy.rlwy.net:25045/railway
      - JWT_SECRET=your_jwt_secret_key
      - RAILWAY_ENVIRONMENT=production
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "gondola.proxy.rlwy.net", "-p", "25045", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge